In [1]:
import pandas as pd
import numpy as np
import time
import pickle
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import RFE
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [2]:
def rfefeature(indep_x,dep_y,n):
    rfelist=[]
    log_model=LogisticRegression(solver='lbfgs')
    RF=RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
    DT=DecisionTreeClassifier(criterion = 'gini', max_features='sqrt',splitter='best',random_state = 0)
    svc_model =SVC(kernel = 'linear', random_state = 0)
    rfemodellist=[log_model,RF,DT,svc_model]
    for i in rfemodellist:
        log_rfe = RFE(i,n)
        log_fit = log_rfe.fit(indep_x,dep_y)
        log_rfe_feature=log_fit.transform(indep_x)
        rfelist.append(log_rfe_feature)
    return rfelist

In [3]:
def split_scalar(indep_x,dep_y):
    x_train,x_test,y_train,y_test=train_test_split(indep_x,dep_y,test_size=0.25,random_state=0)
    sc=StandardScaler()
    x_train=sc.fit_transform(x_train)
    x_test=sc.transform(x_test)
    return x_train,x_test,y_train,y_test

def cm_prediction(classifier,x_test):
    y_pred=classifier.predict(x_test)
#Making confusion matrix
    from sklearn.metrics import confusion_matrix
    cm=confusion_matrix(y_test,y_pred)
    from sklearn.metrics import accuracy_score
    from sklearn.metrics import classification_report
    accuracy=accuracy_score(y_test,y_pred)
    report=classification_report(y_test,y_pred)
    return classifier,accuracy,report,x_test,y_test,cm

def logistic(x_train,y_train,x_test):
    from sklearn.linear_model import LogisticRegression
    classifier=LogisticRegression(random_state=0)
    classifier.fit(x_train,y_train)
    classifier,accuracy,report,x_test,y_test,cm=cm_prediction(classifier,x_test)
    return classifier,accuracy,report,x_test,y_test,cm

def svm_linear(x_train,y_train,x_test):
    from sklearn.svm import SVC
    classifier=SVC(kernel="linear",random_state=0)
    classifier.fit(x_train,y_train)
    classifier,accuracy,report,x_test,y_test,cm=cm_prediction(classifier,x_test)
    return classifier,accuracy,report,x_test,y_test,cm

def svm_NL(x_train,y_train,x_test):
    from sklearn.svm import SVC
    classifier=SVC(kernel="rbf",random_state=0)
    classifier.fit(x_train,y_train)
    classifier,accuracy,report,x_test,y_test,cm=cm_prediction(classifier,x_test)
    return classifier,accuracy,report,x_test,y_test,cm

def Navie(x_train,y_train,x_test):
    from sklearn.naive_bayes import GaussianNB
    classifier=GaussianNB()
    classifier.fit(x_train,y_train)
    classifier,accuracy,report,x_test,y_test,cm=cm_prediction(classifier,x_test)
    return classifier,accuracy,report,x_test,y_test,cm

def knn(x_train,y_train,x_test):
    from sklearn.neighbors import KNeighborsClassifier
    classifier=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
    classifier.fit(x_train,y_train)
    classifier,accuracy,report,x_test,y_test,cm=cm_prediction(classifier,x_test)
    return classifier,accuracy,report,x_test,y_test,cm

def DecisionTree(x_train,y_train,x_test):
    from sklearn.tree import DecisionTreeClassifier
    classifier=DecisionTreeClassifier(criterion="entropy",random_state=0)
    classifier.fit(x_train,y_train)
    classifier,accuracy,report,x_test,y_test,cm=cm_prediction(classifier,x_test)
    return classifier,accuracy,report,x_test,y_test,cm

def RandomForest(x_train,y_train,x_test):
    from sklearn.ensemble import RandomForestClassifier
    classifier=RandomForestClassifier(n_estimators=10, criterion="entropy",random_state=0)
    classifier.fit(x_train,y_train)
    classifier,accuracy,report,x_test,y_test,cm=cm_prediction(classifier,x_test)
    return classifier,accuracy,report,x_test,y_test,cm

In [4]:
def rfe_classification(acclog,accsvm1,accsvmn1,accknn,accnav,accdes,accrf):
    rfedataframe=pd.DataFrame(index=["Logistic","SVC","Random","DecisionTree"],columns=["Logistic","SVM1","SVMn1",
                                                        "KNN","Navie","Decision","Random"])
    for number,idex in enumerate(rfedataframe.index):
        rfedataframe["Logistic"][idex]=acclog[number]
        rfedataframe["SVM1"][idex]=accsvm1[number]
        rfedataframe["SVMn1"][idex]=accsvmn1[number]
        rfedataframe["KNN"][idex]=accknn[number]
        rfedataframe["Navie"][idex]=accnav[number]
        rfedataframe["Decision"][idex]=accdes[number]
        rfedataframe["Random"][idex]=accrf[number]
    return rfedataframe    

In [5]:
dataset1=pd.read_csv("prep.csv",index_col=None)
df2=dataset1
df=pd.get_dummies(df2,drop_first=True)
indep_x=df.drop("classification_yes",axis=1)
dep_y=df["classification_yes"]

In [22]:
rfelist=rfefeature(indep_x,dep_y,7)
acclog=[]
accsvm1=[]
accsvmn1=[]
accknn=[]
accnav=[]
accdes=[]
accrf=[]

C:\Users\saran\anaconda3\envs\AI\lib\site-packages\sklearn\utils\fixes.py:230: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if _joblib.__version__ >= LooseVersion('0.12'):
C:\Users\saran\anaconda3\envs\AI\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\Users\saran\anaconda3\envs\AI\lib\site-packages\sklearn\utils\fixes.py:230: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if _joblib.__version__ >= LooseVersion('0.12'):
C:\Users\saran\anaconda3\envs\AI\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\Users\saran\anaconda3\envs\AI\lib\site-packages\sklearn\utils\fixes.py:230: DeprecationWarning: distutils Version classes are depreca

C:\Users\saran\anaconda3\envs\AI\lib\site-packages\sklearn\utils\fixes.py:230: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if _joblib.__version__ >= LooseVersion('0.12'):
C:\Users\saran\anaconda3\envs\AI\lib\site-packages\sklearn\utils\fixes.py:230: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if _joblib.__version__ >= LooseVersion('0.12'):
C:\Users\saran\anaconda3\envs\AI\lib\site-packages\sklearn\utils\fixes.py:230: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if _joblib.__version__ >= LooseVersion('0.12'):
C:\Users\saran\anaconda3\envs\AI\lib\site-packages\sklearn\utils\fixes.py:230: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if _joblib.__version__ >= LooseVersion('0.12'):
C:\Users\saran\anaconda3\envs\AI\lib\site-packages\sklearn\utils\fixes.py:230: DeprecationWarning: distutils Ver

In [7]:
rfelist

[array([[1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [0., 0., 0., 0.],
        ...,
        [1., 0., 1., 1.],
        [0., 0., 1., 1.],
        [0., 0., 0., 0.]]),
 array([[ 3.        ,  3.07735602, 12.51815562, 38.86890244],
        [ 2.        ,  0.7       , 10.7       , 34.        ],
        [ 1.        ,  0.6       , 12.        , 34.        ],
        ...,
        [ 3.        ,  6.        ,  9.1       , 26.        ],
        [ 0.        ,  6.8       ,  8.5       , 38.86890244],
        [ 0.        ,  1.        , 16.3       , 53.        ]]),
 array([[12.51815562,  1.        ,  1.        ,  0.        ],
        [10.7       ,  1.        ,  1.        ,  0.        ],
        [12.        ,  0.        ,  1.        ,  0.        ],
        ...,
        [ 9.1       ,  1.        ,  1.        ,  1.        ],
        [ 8.5       ,  0.        ,  1.        ,  1.        ],
        [16.3       ,  0.        ,  1.        ,  0.        ]]),
 array([[1., 0., 0., 1.],
        [1., 0., 0., 1.],
   

In [23]:
for i in rfelist:
    x_train,x_test,y_train,y_test=split_scalar(i,dep_y)

    classifier,accuracy,report,x_test,y_test,cm=logistic(x_train,y_train,x_test)
    acclog.append(accuracy)

    classifier,accuracy,report,x_test,y_test,cm=svm_linear(x_train,y_train,x_test)
    accsvm1.append(accuracy)

    classifier,accuracy,report,x_test,y_test,cm=svm_NL(x_train,y_train,x_test)
    accsvmn1.append(accuracy)

    classifier,accuracy,report,x_test,y_test,cm=knn(x_train,y_train,x_test)
    accknn.append(accuracy)

    classifier,accuracy,report,x_test,y_test,cm=Navie(x_train,y_train,x_test)
    accnav.append(accuracy)

    classifier,accuracy,report,x_test,y_test,cm=DecisionTree(x_train,y_train,x_test)
    accdes.append(accuracy)

    classifier,accuracy,report,x_test,y_test,cm=RandomForest(x_train,y_train,x_test)
    accrf.append(accuracy)

result=rfe_classification(acclog,accsvm1,accsvmn1,accknn,accnav,accdes,accrf)


C:\Users\saran\anaconda3\envs\AI\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\saran\anaconda3\envs\AI\lib\site-packages\sklearn\neighbors\base.py:441: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  old_joblib = LooseVersion(joblib_version) < LooseVersion('0.12')
C:\Users\saran\anaconda3\envs\AI\lib\site-packages\sklearn\neighbors\base.py:441: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  old_joblib = LooseVersion(joblib_version) < LooseVersion('0.12')
C:\Users\saran\anaconda3\envs\AI\lib\site-packages\sklearn\utils\fixes.py:230: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if _joblib.__version__ >= LooseVersion('0.12'):
C:\Users\saran\anaconda3\envs\AI\lib\site-packages\sklearn\utils\fixes.py:230: D

In [9]:
result
#4

Logistic  SVM1 SVMn1   KNN Navie Decision Random
Logistic         0.95  0.95  0.95  0.95  0.95     0.95   0.95
SVC              0.97  0.97  0.97  0.97  0.87     0.95   0.97
Random           0.91  0.98  0.92  0.98  0.81     0.98   0.98
DecisionTree     0.96  0.96  0.96  0.96  0.96     0.96   0.96

In [12]:
result
#5

Logistic  SVM1 SVMn1   KNN Navie Decision Random
Logistic         0.98  0.98  0.98  0.98  0.98     0.98   0.98
SVC              0.97  0.97  0.98  0.97  0.91     0.96   0.98
Random           0.92  0.98  0.93  0.94  0.85     0.97   0.98
DecisionTree     0.99  0.99  0.99  0.99  0.99     0.99   0.99

In [15]:
result
#6

Logistic  SVM1 SVMn1   KNN Navie Decision Random
Logistic         0.98  0.98  0.98  0.98  0.98     0.99   0.98
SVC              0.97  0.98  0.99  0.96  0.92     0.95   0.98
Random           0.96  0.96  0.97  0.94  0.85     0.97   0.96
DecisionTree     0.99  0.99  0.99  0.99  0.99     0.99   0.99

In [18]:
result
#3

Logistic  SVM1 SVMn1   KNN Navie Decision Random
Logistic         0.94  0.94  0.94  0.94  0.94     0.94   0.94
SVC              0.94  0.94  0.94  0.94   0.9     0.91   0.92
Random           0.97  0.98  0.98  0.98  0.79     0.97   0.97
DecisionTree     0.87  0.87  0.87  0.87  0.87     0.87   0.87

In [21]:
result
#2

Logistic  SVM1 SVMn1   KNN Navie Decision Random
Logistic         0.84  0.84  0.84  0.84  0.84     0.84   0.84
SVC              0.91  0.92  0.92  0.94  0.85     0.92    0.9
Random           0.95  0.94  0.94  0.94   0.7     0.94   0.94
DecisionTree     0.74  0.74  0.74  0.74  0.74     0.74   0.74

In [24]:
result
#7

Logistic  SVM1 SVMn1   KNN Navie Decision Random
Logistic         0.98  0.98  0.98  0.96  0.98     0.99   0.98
SVC              0.99  0.98  0.98  0.98  0.91     0.96   0.96
Random           0.93  0.96  0.96  0.94  0.88     0.97   0.95
DecisionTree     0.99  0.99  0.99  0.99  0.99        1   0.99